### PR TITLE
Add cncmill

### PR DESCRIPTION
**Pull request by Swwils**
I dont know the mac or IP yet.

### CODE REVIEW

**Comment by ultrafez** [comment]
Looks like you've missed updating the DHCP config - see [this commit](https://github.com/pbrook/lhs-marvin/commit/7d33b3e62bd2f84f6471a8deca9b194ef51ed4cb) for an example of how the laser cutter was added.

Also please squash your commits to keep the git history tidy.

**Comment by ultrafez** [comment]
Also to maintain consistency with what's already there, you need to use tab characters to separate the columns

**Comment by Swwils** [comment]
I cant squash whilst doing a squit

**Comment by Swwils** [comment]
done and done

**Comment by Swwils** [comment]
Thanks,

Record this historic moment as the only merge that has been written entirely on a toilet.

**Pull request merged**
