### PR TITLE
Bumped RFID reader gain

### PR DESCRIPTION
**Pull request by callumsnowden**
Upped the reader gain to the maximum available value.

Fixed issue compiling in Arduino IDE with static void declaration.

### CODE REVIEW

**Review by ultrafez — APPROVED** [review]
Looks good to me, although I have no experience with the MFRC522 library. What's the default gain?

**Comment by callumsnowden** [comment]
Unsure of the default reader gain, but this change bumps the reader to it's maximum possible value of 48dB

**Comment by ultrafez** [comment]
Is this what's flashed onto the door Arduino at the moment then? If so, it might be handy to write up some of the details on how you flashed it on the Marvin page on the Wiki.

**Comment by callumsnowden** [comment]
This is the current door firmware, correct. I'll write the flashing details up in a bit on the wiki, it would be particularly useful after I spent time battling it again the other day myself!

**Pull request closed without merging**
